=== MicrosoftEdge/Status/scripts/schema.json
{
  "$schema": "http://json-schema.org/schema#",
  "definitions": {
    "feature_categories": {
      "enum": [
        "Accessibility",
        "CSS",
        "DOM",
        "Device",
        "File APIs",
        "Graphics",
        "JavaScript",
        "Misc",
        "Multimedia",
        "Network / Connectivity",
        "Offline / Storage",
        "Performance",
        "Realtime / Communication",
        "Security",
        "User input",
        "Web Components"
      ],
      "type": "string"
    },
    "feature_priority": {
      "enum": [
        "High",
        "Low",
        "Medium"
      ],
      "type": "string"
    },
    "implementation_statuses": {
      "enum": [
        "Behind a flag",
        "Deprecated",
        "Enabled by default",
        "In Development",
        "No active development",
        "No public signals",
        "Not currently planned",
        "Not Supported",
        "Prefixed",
        "Preview Release",
        "Removed",
        "Shipped",
        "Under Consideration"
      ],
      "type": "string"
    },
    "standard_statuses": {
      "enum": [
        "De-facto standard",
        "Established standard",
        "Working draft or equivalent",
        "Editor's draft",
        "Public discussion",
        "No public standards discussion"
      ],
      "type": "string"
    },
    "url": {
      "format": "uri",
      "type": "string"
    },
    "vendor_views": {
      "properties": {
        "additionalProperties": false,
        "text": {
          "$ref": "#/definitions/implementation_statuses"
        },
        "value": {
          "maximum": 12,
          "minimum": 1,
          "type": "number"
        }
      },
      "required": [
        "text"
      ],
      "type": "object"
    }
  },
  "description": "Schema for Microsoft Edge platform status JSON",
  "items": {
    "additionalProperties": false,
    "type": "object",
    "properties": {
      "category": {
        "$ref": "#/definitions/feature_categories"
      },
      "demo": {
        "$ref": "#/definitions/url"
      },
      "ff_views": {
        "$ref": "#/definitions/vendor_views"
      },
      "ff_views_link": {
        "$ref": "#/definitions/url"
      },
      "id": {
        "type": "number"
      },
      "ieStatus": {
        "additionalProperties": false,
        "properties": {
          "flag": {
            "type": "boolean"
          },
          "iePrefixed": {
            "minLength": 1,
            "type": "string"
          },
          "ieUnprefixed": {
            "minLength": 1,
            "type": "string"
          },
          "priority": {
            "$ref": "#/definitions/feature_priority"
          },
          "text": {
            "$ref": "#/definitions/ximplementation_statuses"
          }
        },
        "required": [
          "text"
        ]
      },
      "impl_status_chrome": {
        "$ref": "#/definitions/implementation_statuses"
      },
      "link": {
        "$ref": "#/definitions/url"
      },
      "msdn": {
        "$ref": "#/definitions/url"
      },
      "name": {
        "minLength": 1,
        "type": "string"
      },
      "opera_views": {
        "$ref": "#/definitions/vendor_views"
      },
      "shipped_opera_milestone": {
        "type": "boolean"
      },
      "safari_views": {
        "$ref": "#/definitions/vendor_views"
      },
      "safari_views_link": {
        "$ref": "#/definitions/url"
      },
      "spec": {
        "minLength": 1,
        "type": "string"
      },
      "standardStatus": {
        "$ref": "#/definitions/standard_statuses"
      },
      "summary": {
        "minLength": 20,
        "type": "string"
      },
      "uservoiceid": {
        "type": "number"
      }
    }
  },
  "required": [
    "category",
    "ieStatus",
    "name",
    "summary"
  ],
  "type": "array"
}

=== MicrosoftEdge/Status/status.json
[
  {
    "name": "Secure Contexts",
    "category": "Security",
    "link": "https://www.w3.org/TR/secure-contexts/",
    "summary": "As the web enables more powerful apps, features which enable those apps should only be enabled in contexts which meet a specific security level. This also exposes the APIs that identify if you’re in a secure context.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Shipped",
      "ieUnprefixed": "15063"
    },
    "id": 6021277022158848
  },
  {
    "name": "Font Variation Properties with OpenType Variable Font Support",
    "category": "CSS",
    "link": "https://drafts.csswg.org/css-fonts-4/#font-variation-props",
    "summary": "Allows multiple instances of fonts to be defined by interpolating glyph outlines along different axis.",
    "standardStatus": "Editor's draft",
    "ieStatus": {
      "text": "In Development"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "ff_views": {
      "text": "In Development",
      "value": 2
    },
    "id": 4708676673732608,
    "uservoiceid": 19176292
  },
  {
    "name": "font-variant longhands",
    "category": "CSS",
    "link": "https://drafts.csswg.org/css-fonts/#font-variant-caps-prop",
    "summary": "Allows authors to utilize longhand properties of font-variant-caps, font-variant-ligatures, font-variant-numeric, font-variant-alternates, font-variant-east-asian, font-variant-position for font selection and adjustments rather than utilizing lower level props such as font-feature-settings.",
    "standardStatus": "Editor's draft",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Medium"
    },
    "id": 5678497057996800
  },
  {
    "name": "SVG Accessibility API Mappings",
    "category": "Misc",
    "link": "https://www.w3.org/TR/svg-aam-1.0/",
    "summary": "Defines how user agents map SVG markup to platform accessibility application programming interfaces.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Medium"
    }
  },
  {
    "name": "Digital Publishing Accessibility API Mappings",
    "category": "Misc",
    "link": "https://www.w3.org/TR/dpub-aam-1.0/",
    "summary": "Defines how user agents map the Digital Publishing WAI-ARIA Module markup to platform accessibility APIs.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Medium"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "ff_views": {
      "text": "Enabled by default",
      "value": 2
    }
  },
  {
    "name": "-webkit-text-stroke",
    "category": "CSS",
    "link": "https://compat.spec.whatwg.org/#the-webkit-text-stroke",
    "summary": "The -webkit-text-stroke property sets the stroke width and color of an element’s text.",
    "standardStatus": "Established standard",
    "ieStatus": {
      "text": "In Development"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "impl_status_chrome": "Enabled by default",
    "ff_views": {
      "text": "Enabled by default",
      "value": 2
    },
    "shipped_opera_milestone": true,
    "msdn": "https://developer.mozilla.org/docs/Web/CSS/-webkit-text-stroke"
  },
  {
    "name": "WebVR",
    "category": "Graphics",
    "link": "https://w3c.github.io/webvr/",
    "summary": "Support for Virtual Reality applications on the web using head-mounted displays. The WebVR 1.1 API is fully supported in Microsoft Edge. Viewing WebVR content requires a Windows Mixed Reality headset, or the Windows Mixed Reality Portal Simulator (accessible via Developer Mode in the Windows 10 Creators Update).",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Shipped",
      "ieUnprefixed": "15002"
    },
    "id": 4532810371039232,
    "msdn": "https://developer.mozilla.org/docs/Web/API/WebVR_API",
    "uservoiceid": 7119843
  },
  {
    "name": "requestIdleCallback",
    "category": "Performance",
    "link": "https://www.w3.org/TR/requestidlecallback/",
    "summary": "Allows developers to cooperatively schedule background tasks to avoid introducing delays with high priority tasks in the same event loop.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Medium"
    },
    "spec": "requestidlecallback",
    "msdn": "https://developer.mozilla.org/docs/Web/API/Window/requestIdleCallback",
    "id": 5572795866021888
  },
  {
    "name": "Support CSS transforms on SVG",
    "category": "Graphics",
    "link": "https://drafts.csswg.org/css-transforms/",
    "summary": "Enable support for CSS transforms on elements and presentational attributes of SVG",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "In Development"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "impl_status_chrome": "Enabled by default",
    "ff_views": {
      "text": "Enabled by default",
      "value": 2
    },
    "shipped_opera_milestone": true,
    "uservoiceid": 257854
  },
  {
    "name": "CSS resize",
    "category": "Graphics",
    "link": "https://drafts.csswg.org/css-ui/#resize",
    "summary": "Allows one to specify whether or not an element is resizable by the user, and if so, along which axis/axes",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "impl_status_chrome": "Enabled by default",
    "ff_views": {
      "text": "Enabled by default",
      "value": 2
    },
    "shipped_opera_milestone": true,
    "uservoiceid": 6513977
  },
  {
    "name": "CSS outline-offset",
    "category": "Graphics",
    "link": "https://drafts.csswg.org/css-ui/#outline-offset",
    "summary": "Allows you to define an offset from the border box for your outline",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Shipped",
      "ieUnprefixed": "15042"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    },
    "impl_status_chrome": "Enabled by default",
    "ff_views": {
      "text": "Enabled by default",
      "value": 2
    },
    "shipped_opera_milestone": true,
    "msdn": "https://developer.mozilla.org/docs/Web/CSS/outline-offset",
    "uservoiceid": 6517094
  },
  {
    "name": "Frame Timing",
    "category": "Performance",
    "link": "https://www.w3.org/TR/frame-timing/",
    "summary": "An interface for web applications to access runtime performance information of the browser event loop.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
    "spec": "frame-timing",
    "msdn": "https://developer.mozilla.org/docs/Web/API/PerformanceFrameTiming",
    "id": 5558926443544576
  },
  {
    "name": "Performance Observer",
    "category": "Performance",
    "link": "https://w3c.github.io/performance-timeline/#the-performanceobserver-interface",
    "summary": "An interface to observe the performance timeline (https://w3c.github.io/performance-timeline) and receive notifications of new performance entries as they are recorded.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Medium"
    },
    "spec": "performance-timeline-2",
    "msdn": "https://developer.mozilla.org/docs/Web/API/PerformanceObserver",
    "id": 5945504202489856
  },
  {
    "name": "CSS Containment",
    "category": "Performance",
    "link": "https://drafts.csswg.org/css-containment/",
    "summary": "A primitive for isolating style, layout, and paint. This will allow web developers to opt into the various aspects of the pipeline, allowing for UA optimizations.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
    "id": 6522186978295808
  },
  {
    "name": "Initial Letter",
    "category": "CSS",
    "link": "https://drafts.csswg.org/css-inline/#sizing-drop-initials",
    "summary": "Allows the author to set the size and depth at which it sinks into the surrounding text.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
    "safari_views": {
      "text": "Shipped",
      "value": 1
    }
  },
  {
    "name": "Intersection Observer",
    "category": "Performance",
    "link": "https://wicg.github.io/IntersectionObserver/",
    "summary": "An interface to allow a web developer to asynchronously query the position of an element with respect to other elements or the global viewport.",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Shipped",
      "ieUnprefixed": "14986"
    },
    "spec": "intersection-observer",
    "msdn": "https://developer.mozilla.org/docs/Web/API/IntersectionObserver",
    "id": 5695342691483648
  },
  {
    "name": "Resize Observer",
    "category": "Performance",
    "link": "https://wicg.github.io/ResizeObserver/",
    "summary": "Allows a web developer to attach an observer to an element and a callback will be fired when that element is resized",
    "standardStatus": "Working draft or equivalent",
    "ieStatus": {
      "text": "Under Consideration",
      "priority": "Low"
    },
    "id": 5705346022637568
  },
  {
    "name": "Server Timing",
    "category": "Performance",
    "link": "https://www.w3.org/TR/server-timing/",
    "summary": "Enables the server to communicate request-response cycle metrics to the user agent, and provides a JavaScript interface to enable applications to access and act on those metrics.",
    "standardStatus": "Working draft or equivalent",
